In [1]:
import os
import pandas as pd
import seaborn as sns
import matplotlib.pylab as plt
import numpy as np

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
df_bike = pd.read_csv('/content/drive/MyDrive/CIV1498 Final Project/Data/cleaned_data3/period_bike.csv')
df_bike = df_bike.drop(columns = ['Unnamed: 0'])
df_bike

,Year,Month,Day,period,total trips,total member,total casual,mean duration
0,2017,1,1,1,69,65,4,593.086957
1,2017,1,1,2,18,18,0,491.555556
2,2017,1,1,3,116,96,20,784.103448
3,2017,1,1,4,171,141,30,697.105263
4,2017,1,1,5,108,92,16,691.777778
...,...,...,...,...,...,...,...,...
8970,2021,11,30,1,135,42,93,612.377778
8971,2021,11,30,2,821,318,503,687.566382
8972,2021,11,30,3,1085,411,674,626.935484
8973,2021,11,30,4,1788,630,1158,695.394295
8974,2021,11,30,5,1085,357,728,641.938249

#clean the weather

In [ ]:
df_weather = pd.read_csv('/content/drive/MyDrive/CIV1498 Final Project/Data/cleaned_data3/period_weather.csv')
df_weather = df_weather.drop(columns = ['Unnamed: 0'])
df_weather = df_weather.drop(df_weather[df_weather['Year']==2021][df_weather[df_weather['Year']==2021]['Month']==12].index)
df_weather

In [6]:
df_weather['Temp (Â°C)'] = df_weather['Temp (Â°C)'].fillna(18.020996)
df_weather['Dew Point Temp (Â°C)'] = df_weather['Dew Point Temp (Â°C)'].fillna(12.730359)
df_weather['Rel Hum (%)'] = df_weather['Rel Hum (%)'].fillna(72.455093)
df_weather['Wind Dir (10s deg)'] = df_weather['Wind Dir (10s deg)'].fillna(19.89462920633175)
df_weather['Wind Spd (km/h)'] = df_weather['Wind Spd (km/h)'].fillna(14.42541)
df_weather['Visibility (km)'] = df_weather['Visibility (km)'].fillna(15.119552)
df_weather['Stn Press (kPa)'] = df_weather['Stn Press (kPa)'].fillna(100.421307)

In [7]:
df_weather.to_csv('/content/drive/MyDrive/CIV1498 Final Project/Data/cleaned_data3/period_weather_2.csv')

In [8]:
df_weather

,Year,Month,Day,period,Temp (Â°C),Dew Point Temp (Â°C),Rel Hum (%),Wind Dir (10s deg),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2017,1,1,1,1.250000,-4.100000,67.666667,25.666667,33.500000,16.10,100.218333,Clear
1,2017,1,1,2,0.075000,-5.000000,68.750000,25.000000,28.750000,16.10,100.857500,Clear
2,2017,1,1,3,2.220000,-5.420000,57.200000,23.800000,20.200000,16.10,101.222000,Clear
3,2017,1,1,4,2.425000,-4.950000,58.250000,22.750000,17.250000,16.10,101.427500,Clear
4,2017,1,1,5,1.000000,-3.040000,74.600000,23.800000,12.600000,16.10,101.704000,Clear
...,...,...,...,...,...,...,...,...,...,...,...,...
8970,2021,11,30,1,-0.533333,-4.533333,74.500000,28.333333,9.166667,16.10,100.428333,Clear
8971,2021,11,30,2,-0.050000,-2.475000,84.750000,20.333333,9.750000,9.35,100.287500,Precipitation
8972,2021,11,30,3,1.480000,-0.080000,89.600000,18.666667,6.000000,13.68,100.130000,Clear
8973,2021,11,30,4,2.650000,0.325000,84.750000,23.750000,16.750000,16.10,100.032500,Clear
8974,2021,11,30,5,3.100000,0.540000,83.400000,25.400000,26.000000,16.10,100.186000,Clear

#concat trip and weather

In [9]:
header = ['Year__', 'Month__', 'Day__', 'period__', 'total trips', 'total member',
       'total casual', 'mean duration']
df_bike.columns = header

In [10]:
df = pd.concat([df_weather, df_bike], axis = 1)

In [11]:
df = df.drop(columns = ['Year__', 'Month__', 'Day__', 'period__'])

In [12]:
df.head()

,Year,Month,Day,period,Temp (Â°C),Dew Point Temp (Â°C),Rel Hum (%),Wind Dir (10s deg),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,total trips,total member,total casual,mean duration
0,2017,1,1,1,1.250,-4.10,67.666667,25.666667,33.50,16.1,100.218333,Clear,69,65,4,593.086957
1,2017,1,1,2,0.075,-5.00,68.750000,25.000000,28.75,16.1,100.857500,Clear,18,18,0,491.555556
2,2017,1,1,3,2.220,-5.42,57.200000,23.800000,20.20,16.1,101.222000,Clear,116,96,20,784.103448
3,2017,1,1,4,2.425,-4.95,58.250000,22.750000,17.25,16.1,101.427500,Clear,171,141,30,697.105263
4,2017,1,1,5,1.000,-3.04,74.600000,23.800000,12.60,16.1,101.704000,Clear,108,92,16,691.777778

In [ ]:
df.to_csv('/content/drive/MyDrive/CIV1498 Final Project/Data/cleaned_data3/period_bike_and_weather.csv')

#add true false weekend

In [13]:
pip install holidays

Requirement already satisfied: holidays in /usr/local/lib/python3.7/dist-packages (0.10.5.2)
Requirement already satisfied: korean-lunar-calendar in /usr/local/lib/python3.7/dist-packages (from holidays) (0.2.1)
Requirement already satisfied: hijri-converter in /usr/local/lib/python3.7/dist-packages (from holidays) (2.2.3)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from holidays) (2.8.2)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from holidays) (1.15.0)
Requirement already satisfied: convertdate>=2.3.0 in /usr/local/lib/python3.7/dist-packages (from holidays) (2.4.0)
Requirement already satisfied: pymeeus<=1,>=0.3.13 in /usr/local/lib/python3.7/dist-packages (from convertdate>=2.3.0->holidays) (0.5.11)

In [14]:
df = pd.read_csv('/content/drive/MyDrive/CIV1498 Final Project/Data/cleaned_data3/period_bike_and_weather.csv')

In [15]:
import datetime
from datetime import date                                          
import holidays

time = []
weekday = []
ca_holidays = holidays.Canada()    
holiday_lst = [] 
weekend_lst = []                    


for idx, row in df.iterrows():
  date = datetime.datetime(row['Year'], row['Month'], row['Day'])
  time.append(date)
  weekday.append(date.weekday())

  #check whether the date is holiday
  holiday_name = ca_holidays.get(date)
  if holiday_name != None: 
    holiday_lst.append(True)
  else:
    holiday_lst.append(False)


df['Time'] = time
df['Weekday'] = weekday
df['is_holiday'] = holiday_lst

In [16]:
is_weekend = (df['Weekday'] == 5) | (df['Weekday'] == 6)
df['is_weekend'] = is_weekend

In [ ]:
df.columns

In [18]:
header = ['Time', 'Year', 'Month', 'Day', 'period', 'Weekday', 'is_holiday', 'is_weekend', 'Temp (Â°C)',
       'Dew Point Temp (Â°C)', 'Rel Hum (%)', 'Wind Dir (10s deg)',
       'Wind Spd (km/h)', 'Visibility (km)', 'Stn Press (kPa)', 'Weather',
       'total trips', 'total member', 'total casual', 'mean duration']
df = df[header]
df

,Time,Year,Month,Day,period,Weekday,is_holiday,is_weekend,Temp (Â°C),Dew Point Temp (Â°C),Rel Hum (%),Wind Dir (10s deg),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,total trips,total member,total casual,mean duration
0,2017-01-01,2017,1,1,1,6,True,True,1.250000,-4.100000,67.666667,25.666667,33.500000,16.10,100.218333,Clear,69,65,4,593.086957
1,2017-01-01,2017,1,1,2,6,True,True,0.075000,-5.000000,68.750000,25.000000,28.750000,16.10,100.857500,Clear,18,18,0,491.555556
2,2017-01-01,2017,1,1,3,6,True,True,2.220000,-5.420000,57.200000,23.800000,20.200000,16.10,101.222000,Clear,116,96,20,784.103448
3,2017-01-01,2017,1,1,4,6,True,True,2.425000,-4.950000,58.250000,22.750000,17.250000,16.10,101.427500,Clear,171,141,30,697.105263
4,2017-01-01,2017,1,1,5,6,True,True,1.000000,-3.040000,74.600000,23.800000,12.600000,16.10,101.704000,Clear,108,92,16,691.777778
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8970,2021-11-30,2021,11,30,1,1,False,False,-0.533333,-4.533333,74.500000,28.333333,9.166667,16.10,100.428333,Clear,135,42,93,612.377778
8971,2021-11-30,2021,11,30,2,1,False,False,-0.050000,-2.475000,84.750000,20.333333,9.750000,9.35,100.287500,Precipitation,821,318,503,687.566382
8972,2021-11-30,2021,11,30,3,1,False,False,1.480000,-0.080000,89.600000,18.666667,6.000000,13.68,100.130000,Clear,1085,411,674,626.935484
8973,2021-11-30,2021,11,30,4,1,False,False,2.650000,0.325000,84.750000,23.750000,16.750000,16.10,100.032500,Clear,1788,630,1158,695.394295
8974,2021-11-30,2021,11,30,5,1,False,False,3.100000,0.540000,83.400000,25.400000,26.000000,16.10,100.186000,Clear,1085,357,728,641.938249

In [19]:
df = df.rename(columns={'Temp (Â°C)': "Mean Temp (Â°C)",
                   "period": "Period",
                   "total trips": "Total Trips",
                   "total member": "Member Trips",
                   "total casual": "Casual Trips",
                   "mean duration": "Mean Trip Duration (sec)",
                   "A": "a",})
df.head(50)

,Time,Year,Month,Day,Period,Weekday,is_holiday,is_weekend,Mean Temp (Â°C),Dew Point Temp (Â°C),Rel Hum (%),Wind Dir (10s deg),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,Total Trips,Member Trips,Casual Trips,Mean Trip Duration (sec)
0,2017-01-01,2017,1,1,1,6,True,True,1.250000,-4.100000,67.666667,25.666667,33.500000,16.100000,100.218333,Clear,69,65,4,593.086957
1,2017-01-01,2017,1,1,2,6,True,True,0.075000,-5.000000,68.750000,25.000000,28.750000,16.100000,100.857500,Clear,18,18,0,491.555556
2,2017-01-01,2017,1,1,3,6,True,True,2.220000,-5.420000,57.200000,23.800000,20.200000,16.100000,101.222000,Clear,116,96,20,784.103448
3,2017-01-01,2017,1,1,4,6,True,True,2.425000,-4.950000,58.250000,22.750000,17.250000,16.100000,101.427500,Clear,171,141,30,697.105263
4,2017-01-01,2017,1,1,5,6,True,True,1.000000,-3.040000,74.600000,23.800000,12.600000,16.100000,101.704000,Clear,108,92,16,691.777778
5,2017-01-02,2017,1,2,1,0,True,False,0.650000,-2.233333,81.000000,5.200000,11.833333,16.100000,101.785000,Clear,32,30,2,582.500000
6,2017-01-02,2017,1,2,2,0,True,False,2.500000,0.300000,85.500000,6.250000,22.500000,15.300000,101.777500,Clear,53,52,1,643.509434
7,2017-01-02,2017,1,2,3,0,True,False,3.880000,0.500000,78.800000,6.400000,26.200000,16.100000,101.628000,Clear,254,235,19,643.645669
8,2017-01-02,2017,1,2,4,0,True,False,3.950000,0.600000,78.750000,7.000000,26.750000,16.100000,101.450000,Clear,278,241,37,650.938849
9,2017-01-02,2017,1,2,5,0,True,False,3.880000,2.300000,89.400000,7.200000,17.600000,14.180000,101.114000,Clear,209,198,11,594.626794
10,2017-01-03,2017,1,3,1,1,False,False,3.883333,3.350000,96.333333,6.166667,19.666667,6.700000,100.700000,Precipitation,35,31,4,737.942857
11,2017-01-03,2017,1,3,2,1,False,False,4.200000,3.900000,98.000000,8.750000,17.000000,9.250000,100.215000,Clear,182,178,4,665.434066
12,2017-01-03,2017,1,3,3,1,False,False,4.300000,4.000000,98.000000,6.400000,16.000000,9.040000,99.776000,Precipitation,194,191,3,628.721649
13,2017-01-03,2017,1,3,4,1,False,False,4.725000,4.250000,96.750000,5.250000,14.250000,14.500000,99.310000,Precipitation,283,280,3,634.091873
14,2017-01-03,2017,1,3,5,1,False,False,4.320000,3.540000,94.600000,21.200000,9.200000,10.300000,98.974000,Precipitation,177,173,4,695.090395
15,2017-01-04,2017,1,4,1,2,False,False,3.266667,2.033333,91.833333,26.666667,17.166667,15.033333,98.751667,Clear,27,27,0,571.000000
16,2017-01-04,2017,1,4,2,2,False,False,3.300000,0.175000,80.000000,25.500000,32.500000,16.100000,98.835000,Clear,291,287,4,630.872852
17,2017-01-04,2017,1,4,3,2,False,False,-0.840000,-7.200000,62.400000,26.200000,47.000000,16.100000,99.076000,Clear,391,376,15,625.521739
18,2017-01-04,2017,1,4,4,2,False,False,-4.575000,-11.275000,60.000000,25.750000,48.000000,16.100000,99.415000,Clear,408,397,11,639.259804
19,2017-01-04,2017,1,4,5,2,False,False,-6.740000,-11.560000,68.800000,25.200000,47.800000,15.140000,99.624000,Clear,278,274,4,589.453237
20,2017-01-05,2017,1,5,1,3,False,False,-6.250000,-10.966667,69.500000,24.500000,46.833333,16.100000,99.835000,Clear,21,21,0,616.380952
21,2017-01-05,2017,1,5,2,3,False,False,-6.775000,-11.325000,70.250000,24.500000,40.750000,16.100000,100.152500,Clear,224,223,1,621.223214
22,2017-01-05,2017,1,5,3,3,False,False,-6.200000,-12.500000,61.400000,25.200000,32.800000,16.100000,100.226000,Clear,311,304,7,605.694534
23,2017-01-05,2017,1,5,4,3,False,False,-6.500000,-12.200000,64.250000,26.750000,26.750000,15.700000,100.185000,Clear,391,384,7,600.186701
24,2017-01-05,2017,1,5,5,3,False,False,-8.400000,-13.640000,66.400000,27.600000,26.400000,16.100000,100.372000,Clear,263,259,4,629.574144
25,2017-01-06,2017,1,6,1,4,False,False,-10.266667,-14.833333,69.500000,27.666667,23.833333,16.100000,100.585000,Clear,37,33,4,651.297297
26,2017-01-06,2017,1,6,2,4,False,False,-11.150000,-15.575000,70.250000,26.750000,24.750000,16.100000,100.805000,Clear,214,210,4,606.808411
27,2017-01-06,2017,1,6,3,4,False,False,-7.400000,-15.940000,51.000000,26.400000,22.800000,16.100000,101.004000,Clear,290,290,0,555.593103
28,2017-01-06,2017,1,6,4,4,False,False,-7.650000,-16.350000,50.250000,27.750000,24.000000,16.100000,101.215000,Clear,399,377,22,641.609023
29,2017-01-06,2017,1,6,5,4,False,False,-9.780000,-16.220000,60.000000,28.200000,19.400000,16.100000,101.554000,Clear,235,233,2,606.514894
30,2017-01-07,2017,1,7,1,5,False,True,-10.966667,-15.550000,69.333333,28.666667,14.500000,16.100000,101.743333,Clear,39,37,2,580.358974
31,2017-01-07,2017,1,7,2,5,False,True,-11.475000,-15.225000,74.250000,26.500000,9.250000,16.100000,101.820000,Clear,26,26,0,555.807692
32,2017-01-07,2017,1,7,3,5,False,True,-7.720000,-13.220000,65.200000,27.000000,13.800000,16.100000,101.754000,Clear,215,213,2,560.581395
33,2017-01-07,2017,1,7,4,5,False,True,-8.250000,-15.475000,56.500000,27.250000,23.750000,16.100000,101.637500,Clear,181,178,3,632.629834
34,2017-01-07,2017,1,7,5,5,False,True,-9.900000,-15.320000,65.200000,24.600000,32.800000,16.100000,101.586000,Clear,92,88,4,553.315217
35,2017-01-08,2017,1,8,1,6,False,True,-9.150000,-13.383333,71.833333,26.666667,32.000000,16.100000,101.346667,Clear,39,39,0,637.051282
36,2017-01-08,2017,1,8,2,6,False,True,-9.625000,-17.150000,55.000000,29.750000,24.500000,16.100000,101.690000,Clear,20,18,2,469.000000
37,2017-01-08,2017,1,8,3,6,False,True,-9.140000,-17.660000,51.000000,30.800000,30.400000,16.100000,102.106000,Clear,158,156,2,494.291139
38,2017-01-08,2017,1,8,4,6,False,True,-9.775000,-17.300000,55.000000,31.250000,17.500000,16.100000,102.452500,Clear,159,157,2,510.842767
39,2017-01-08,2017,1,8,5,6,False,True,-10.140000,-15.840000,63.800000,27.000000,16.400000,16.100000,102.688000,Clear,109,108,1,549.330275
40,2017-01-09,2017,1,9,1,0,False,False,-7.366667,-13.116667,64.000000,24.666667,26.666667,16.100000,102.506667,Clear,19,19,0,413.578947
41,2017-01-09,2017,1,9,2,0,False,False,-5.275000,-10.025000,69.500000,21.500000,39.750000,16.100000,102.290000,Precipitation,277,276,1,633.061372
42,2017-01-09,2017,1,9,3,0,False,False,-3.760000,-8.620000,69.400000,22.000000,41.800000,15.140000,101.960000,Clear,317,313,4,583.290221
43,2017-01-09,2017,1,9,4,0,False,False,-2.375000,-8.925000,61.000000,24.000000,29.750000,16.100000,101.867500,Clear,451,444,7,612.075388
44,2017-01-09,2017,1,9,5,0,False,False,-1.760000,-7.160000,66.800000,22.800000,30.200000,16.100000,101.916000,Clear,297,293,4,631.717172
45,2017-01-10,2017,1,10,1,1,False,False,-0.716667,-6.516667,65.000000,20.000000,24.833333,12.883333,101.696667,Clear,27,26,1,664.222222
46,2017-01-10,2017,1,10,2,1,False,False,-0.950000,-2.325000,90.500000,15.750000,21.500000,2.200000,101.322500,Precipitation,107,107,0,742.635514
47,2017-01-10,2017,1,10,3,1,False,False,0.580000,-2.500000,80.200000,13.600000,19.200000,12.240000,100.720000,Precipitation,142,141,1,635.443662
48,2017-01-10,2017,1,10,4,1,False,False,2.350000,1.525000,94.250000,15.500000,21.250000,12.500000,99.932500,Precipitation,135,135,0,682.681481
49,2017-01-10,2017,1,10,5,1,False,False,5.260000,4.020000,91.600000,19.200000,26.200000,10.980000,99.204000,Precipitation,113,112,1,619.460177

In [ ]:
df.to_csv('/content/drive/MyDrive/CIV1498 Final Project/Data/cleaned_data3/period_bike_and_weather_new_header.csv')

In [ ]:
df.head(50)

In [20]:
df

,Time,Year,Month,Day,Period,Weekday,is_holiday,is_weekend,Mean Temp (Â°C),Dew Point Temp (Â°C),Rel Hum (%),Wind Dir (10s deg),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,Total Trips,Member Trips,Casual Trips,Mean Trip Duration (sec)
0,2017-01-01,2017,1,1,1,6,True,True,1.250000,-4.100000,67.666667,25.666667,33.500000,16.10,100.218333,Clear,69,65,4,593.086957
1,2017-01-01,2017,1,1,2,6,True,True,0.075000,-5.000000,68.750000,25.000000,28.750000,16.10,100.857500,Clear,18,18,0,491.555556
2,2017-01-01,2017,1,1,3,6,True,True,2.220000,-5.420000,57.200000,23.800000,20.200000,16.10,101.222000,Clear,116,96,20,784.103448
3,2017-01-01,2017,1,1,4,6,True,True,2.425000,-4.950000,58.250000,22.750000,17.250000,16.10,101.427500,Clear,171,141,30,697.105263
4,2017-01-01,2017,1,1,5,6,True,True,1.000000,-3.040000,74.600000,23.800000,12.600000,16.10,101.704000,Clear,108,92,16,691.777778
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8970,2021-11-30,2021,11,30,1,1,False,False,-0.533333,-4.533333,74.500000,28.333333,9.166667,16.10,100.428333,Clear,135,42,93,612.377778
8971,2021-11-30,2021,11,30,2,1,False,False,-0.050000,-2.475000,84.750000,20.333333,9.750000,9.35,100.287500,Precipitation,821,318,503,687.566382
8972,2021-11-30,2021,11,30,3,1,False,False,1.480000,-0.080000,89.600000,18.666667,6.000000,13.68,100.130000,Clear,1085,411,674,626.935484
8973,2021-11-30,2021,11,30,4,1,False,False,2.650000,0.325000,84.750000,23.750000,16.750000,16.10,100.032500,Clear,1788,630,1158,695.394295
8974,2021-11-30,2021,11,30,5,1,False,False,3.100000,0.540000,83.400000,25.400000,26.000000,16.10,100.186000,Clear,1085,357,728,641.938249